### ISSUE TITLE
Agregar nuevo reto

### ISSUE THREAD

**Issue by SelassieAMC** [fluidsignal/training#1043]
Buenos dias,

Ingrese el PR para crear un nuevo reto de wechall "Yourself PHP" y la solucion, pero fue rechazado. Me podrias indicar que proceso debo seguir para corregir el error.

**Comment by ralvarezatfluid** [comment]
Los retos deben pasar en verde el intwgrador continuo. Investigue sobre travis, y mire los PR de otros talentos q lo ha enviado, unos q han pasado y otros que no, basicamente el integrador continuo verifica automaticamente las reglas q estan escritas en el Readme del repositorio
