### ISSUE TITLE
Mi código no pasa Travis CI

### ISSUE THREAD

**Issue by Audrum** [fluidsignal/training#1340]
Buenas tardes, un ejemplo lo tengo con el siguiente código en lenguaje python, [aquí pueden ver el pull request](https://github.com/fluidsignal/training/pull/1338):

![image](https://cloud.githubusercontent.com/assets/5705313/26175807/8aca3344-3b19-11e7-87e6-d294d60d4db5.png)

Lo tengo con espacios sin tabulaciones y aparentemente creo que está bien en cuanto a las demás directrices, sin embargo, al subirlo al repositorio, Travis no lo pasa. Al consultar los detalles de Travis [aquí](https://travis-ci.org/fluidsignal/training/builds/233390869?utm_source=github_status&utm_medium=notification) lo único raro que encuentro es esto:

![image](https://cloud.githubusercontent.com/assets/5705313/26175883/d3b9882a-3b19-11e7-8abf-df0a17ed4b57.png)

Sin embargo, como soy nuevo con Travis, no logro interpretar exactamente si ese es el error o existe otro más.

Quedo atento a sus comentarios y agradezco su atención.

Gracias.

**Comment by ralvarezatfluid** [comment]
Ek integrador tiene un log detallado q puedes ver porque falla. Ver una pestana q aparece en el
