### ISSUE TITLE
Error de travis en el nombre del modulo.

### ISSUE THREAD

**Issue by 3Rr0r404a** [fluidsignal/training#1397]
Saludos,

Gracias a la ayuda que me dieron pude ver cuales eran los problemas que tenia para subir las soluciones de retos de programación pero resulta que travis me marca error con el nombre del modulo (nombre del archivo) al parecer no puede empezar por numero y me marca error, así que mi solución fue cambiar el nombre a error404a.py pero se que el archivo debe tener el mismo nombre que mi usuario. Rafael me dijo que cambiara mi nombre de usuario pero le manifesté que ya había subido las soluciones de los retos de hacking, sin embargo igual hice el intento pero resulta que si cambio mi nombre de usuario github pierdo mi avance en codeabby. 

Por lo anterior no he seguido subiendo retos. Por favor ayúdenme a encontrar una solución muchas gracias

**Comment by ralvarezatfluid** [comment]
renombrar todos los retos subidos para q queden error404a.  el usuario q debe cambiar es solo el de github no el de codeabbey
