### ISSUE TITLE
Errores en Travis al ejecutar "scons folders" luego de un merge con fluidsignal/training/master

### ISSUE THREAD

**Issue by ErisoHV** [fluidsignal/training#1466]
El día de ayer realicé un merge para actualizar mi fork. El merge incluyó [estos cambios](https://github.com/ErisoHV/training/commit/ffa29864544ebc7545439b7a58e6d21f2ba76649)

Travis realizó un build en mi repositorio con estos cambios, y falló dando estos errores:

`build_folders(["build/codeabbey/055/folder.txt"], ["challenges/codeabbey/055/DATA.txt", "challenges/codeabbey/055/OTHERS.txt", "challenges/codeabbey/055/jhonyvilla.java", "challenges/codeabbey/055/pach092.py", "challenges/codeabbey/055/LINK.txt"])
Starting audit...
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:0: Missing 
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:6:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:7:1: '{' at column 1 should be on the previous line. [LeftCurly]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:8: Line has trailing spaces. [RegexpSingleline]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:8:5: Missing a Javadoc comment. [JavadocMethod]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:8:29: Parameter args should be final. [FinalParameters]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:9:5: '{' at column 5 should be on the previous line. [LeftCurly]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:10: Line has trailing spaces. [RegexpSingleline]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:13: Line has trailing spaces. [RegexpSingleline]
.........
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:43:17: '{' at column 17 should be on the previous line. [LeftCurly]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:45:35: '+' is not preceded with whitespace. [WhitespaceAround]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:45:36: '+' is not followed by whitespace. [WhitespaceAround]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:46: Line has trailing spaces. [RegexpSingleline]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:46:26: '+' is not preceded with whitespace. [WhitespaceAround]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:46:27: '+' is not followed by whitespace. [WhitespaceAround]
[ERROR] /home/travis/build/ErisoHV/training/challenges/codeabbey/055/jhonyvilla.java:49: Line has trailing spaces. [RegexpSingleline]
Audit done.
Checkstyle ends with 71 errors.
java lint Failed - exit code: 71
scons: *** [build/codeabbey/055/folder.txt] Error 1
scons: building terminated because of errors.`

**Comment by ralvarezatfluid** [comment]
erika soluciona el error con un workaround para que pase el build y creo q podras enviar un PR mientras terminamos. cuando estas en medellin para conocerte personalmente? el prox lunes?

**Comment by jaguir11** [comment]
solucionado con merge #1470  .. Favor cerrar.
