### ISSUE TITLE
Dudas con los archivos others.txt

### ISSUE THREAD

**Issue by raguar94** [fluidsignal/training#1687]
Cordial saludo.

Tengo entendido que hay que buscar 40 retos que no tengan una solución dentro del repositorio y que si la tengan en Internet y añadir el enlace de la solución en un archivo others.txt. Mi pregunta es: si el reto tiene la solución dentro de la carpeta donde se encuentra, indiferente de que exista no el archivo others.txt, ¿debo buscar entonces una carpeta que tenga un reto que no tenga solución aun?

Gracias por su atención.

**Comment by ralvarezatfluid** [comment]
es valido crear archivos others incluso cuando ese reto ya tiene solucion en la carpeta

tambien es valido incluso anadir un enlace nuevo al archivo incluso si exite others, desde q el enlace sea valido y contenga una solucion no identificada al reto
