### ISSUE TITLE
Como resolver error Missing package-info.java file. 

### ISSUE THREAD

**Issue by sjcantillo** [fluidsignal/training#1692]
Hola, me pueden colaborar en resolver ese error que me aparece cuando subo un archivo .java y arroja ese único error al validar el código estático

**Comment by ralvarezatfluid** [comment]
la idea es q puedas resolver tu solo dicho problema, de eso se trata la etapa. ya vimos que error te saca y el error mismo es la pista de lo que debes corregir para reparar.
