### ISSUE TITLE
Duda con los retos de programación

### ISSUE THREAD

**Issue by raguar94** [fluidsignal/training#1827]
Cordial saludo, en las instrucciones para los retos informáticos ustedes colocaron, que hay que resolver 10 retos de programación que no tengan solución en el repositorio ni en los archivos de OTHERS.txt, sin embargo, mas adelante colocan que para los retos de lenguajes de programación, una solución es válida si no ha sido resuelta en el lenguaje que usted pretende solucionarlo. de lo anterior me surge la siguiente pregunta es: si uno de los retos de programación seleccionados esta resuelto en un lenguaje de programación X en el repositorio, si resuelvo el mismo reto en un lenguaje de programación diferente ¿es valido el aporte?.

**Comment by ralvarezatfluid** [comment]
es valido
