### ISSUE TITLE
#2023 opened an hour ago by javilag

### ISSUE THREAD

**Issue by javilag** [fluidsignal/training#2025]
Muy buenos días, 

el siguiente mensaje es para preguntar por que el ci aun no me acepta el pull request, ya he cambiado todos los links al raw indicado, aunque siendo sincero no se si me haya faltado algún link,¿si es así de pronto me podrías decir en cual commit por favor? de todas maneras estaré revisando por si se me fue algún espacio o algo. 

Muchas gracias.

**Comment by ralvarezatfluid** [comment]
ver log travis,
