### ISSUE TITLE
Inquietud al subir archivos

### ISSUE THREAD

**Issue by thrownshadow** [fluidsignal/training#897]
buenos dias, 

Actualmente me encuentro en la etapa de retos informáticos, de algunas de las paginas de retos que ya tienen, he encontrado varios a los que tengo respuestas pero nose como poner la carpeta para póder poner los retos que tengo solución.

**Comment by ralvarezatfluid** [comment]
si el sitio o el reto no tiene carpeta, simplemente lo creas y lo subes en el commit y luego con un pull request.
