### ISSUE TITLE
lectura de libro

### ISSUE THREAD

**Issue by colombianoXD** [fluidsignal/training#903]
Buenas tarde tengo una duda he leído un libro de seguridad informática de kali linux pero al momento que voy a enviar mi reporte de progreso me pide el build. pero no se que enviar en este campo si lo único que hice fue leer un libro

**Comment by ralvarezatfluid** [comment]
La etapa de retos es resolver retos no resueltos, el libro es interesante que lo leas pero es una de tantas formas de llegar a los retos. En la etapa q estas no hay q reportar la lectura.
