### ISSUE TITLE
Inquyietud valor build

### ISSUE THREAD

**Issue by thrownshadow** [fluidsignal/training#972]
Buenas tardes,

Quisiera saber cómo se obtiene el valor build para poder completar el formulario de entrenamiento.

También encontré una página de hacking y que brinda retos pero esta no se encuentra dentro de las páginas de wechall para dar ranking, esta puedo utilizarla para el proceso de selección.

**Comment by ralvarezatfluid** [comment]
El build se genera al registrarse en travisci y hacer pull request, de esta forma travis se dispara y verifica el codigo que estas tratando de enviar.

Si cumple los demas requisitos enviados en los terminos puedes resolver retos de ahi y mantenerte en un ranking inicial de wechall.

Lo importante es resolver retos no resueltos, subir las soluciones en el formato definido y que dichas soluciones integren en el integrador
